## Go function to execute to generate the name of the OAuth2 app
# package main

# import (
# 	"fmt"
# 	"strings"
# 	"hash/fnv"
# 	"encoding/base32"
# )

# var encoding = base32.NewEncoding("abcdefghijklmnopqrstuvwxyz234567")

# func main() {
# 	clientName := "nginx-prod"
# 	toDecodeString := []byte(clientName)
# 	encodedString := strings.TrimRight(encoding.EncodeToString(fnv.New64().Sum(toDecodeString)), "=")
# 	fmt.Print(encodedString)
# }

apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: nztws3tyfvyhe33ezpzjzzeeeirsk #this need to be special encoding based on the ID of the client: https://github.com/dexidp/dex/issues/1606#issuecomment-569130595
id: nginx-prod
name: "Nginx proxy"
secret: "ZXhhbXBsZS1hcsvtc2VjcmV0"
redirectURIs:
  - https://proxy.mycompany.com/oauth2/callback
